-- Drop old tables
DROP TABLE files;
DROP TABLE word_counts;

-- Create the input table
CREATE TABLE files (line STRING);

-- Load data into the table
LOAD DATA LOCAL INPATH '/root/input.txt' INTO TABLE files;

-- Generate output and save it in a table
CREATE TABLE word_counts AS
SELECT word, COUNT(word) as no_of_words FROM
(SELECT explode(split(line,' ')) AS word FROM files) AS w 
GROUP BY word
ORDER BY no_of_words DESC;
