apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  # replicas: 3
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: apiserver
          image: docker.io/sulbha24/simple-blog-api-app-image2
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_USERNAME
              value: postgres
            - name: POSTGRES_HOST
              value: postgres-cluster-ip-service
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_DB
              value: simple_blog_api
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: POSTGRES_PASSWORD

# TODO: Add Env Vars for Postgres