apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
    - role: control-plane
      kubeadmConfigPatches:
          - |
              kind: InitConfiguration
              nodeRegistration:
                kubeletExtraArgs:
                  node-labels: "ingress-ready=true"
      extraPortMappings:
          - containerPort: 31515
            hostPort: 31515
            protocol: tcp
          - containerPort: 3000
            hostPort: 30003
            protocol: tcp
          - containerPort: 80
            hostPort: 30000
            protocol: tcp
    - role: worker