services:
    #Postgres Database
    postgres:
        #image: 'postgres:latest'
        image: docker.io/postgres
        
        environment:
            - POSTGRES_PASSWORD=postgres_password
    #Redis Database
    redis:
        #image: 'redis:latest'
        image: docker.io/redis
        command: ["redis-server", "--protected-mode", "no"]
    
    #Express API server
    api:
        #build:
        #    context: ./server
        build: ./server       
        image: docker.io/16052019/complex-api            
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432

    #Worker Service
    worker:
        build:
            context: ./worker
        image: docker.io/16052019/complex-worker     
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379

    #React client
    client:
        build: ./client
        image: docker.io/16052019/complex-client     

    # Ngnix controller
    nginx:	
        depends_on:	
            - api	
            - client	
        restart: always	
        build: ./nginx	
        ports:	
            - '8003:80'

