services:
  # Redis database
  redis-server:
      image: redis
      volumes:
          - ./redis:/data
      command: ["redis-server", "--protected-mode", "no", "--save", "1 1"]
  # Node application
  node-app:
      build: ./
      image: docker.io/16052019/visits
      ports:
            - "8081:8081"
