---
- hosts: local
  become: true
  tasks:
      - name: Install required components
        apt:
            name:
                - git
                - maven
                - openjdk-17-jdk
            state: present
      - name: Clone Maven repo
        git:
            repo: https://github.com/sulpawde/FST_JUnit_Project.git
            dest: /home/ubuntu/ansible/MavenProject/FST_M2_Junit_Sample_Project

      - name: Run Maven tests
        command: mvn clean test
        args:
            chdir: /home/ubuntu/ansible/MavenProject/FST_M2_Junit_Sample_Project